CREATE TABLE input
(
    COL_INT INT,
    COL_FLOAT FLOAT,
    COL_TIMESTAMP TIMESTAMP,
    COL_TIMESTAMP_MILLIS TIMESTAMP,
    COL_TIMESTAMP_MICROS TIMESTAMP,
    PRIMARY KEY(COL_INT)
)
PARTITION BY HASH PARTITIONS 16
STORED AS KUDU;